#!/usr/bin/env python3
"""
Font License Database Seeder

Populates the fonts and font_aliases tables with 300+ fonts including:
- 200+ Popular Chinese fonts (方正, 汉仪, 华康, 站酷, 思源, 阿里普惠, 造字工房, etc.)
- 100+ English fonts (Google Fonts, Adobe Fonts, system fonts, etc.)

Usage:
    python scripts/seed_fonts.py

Requires DATABASE_URL in .env or environment.
"""

import sys
import os

# Add the parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.font import Font, FontAlias
from app.core.database import Base

# ── Font Data ──────────────────────────────────────────────────────────

FONTS_DATA = [
    # ═══════════════════════════════════════════════════════════════
    # 方正字库 (FounderType) — Most require paid license for commercial use
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "方正黑体",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["FZHeiTi", "FZHT", "FounderType Hei Ti"],
        "notes": "商业使用需购买方正字库授权",
    },
    {
        "name": "方正书宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZShuSong", "FZSS", "FounderType Book Song"],
    },
    {
        "name": "方正仿宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZFangSong", "FZFS", "FounderType Fang Song"],
    },
    {
        "name": "方正楷体",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZKaiTi", "FZKT", "FounderType Kai Ti"],
    },
    {
        "name": "方正中等线",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZZhongDengXian"],
    },
    {
        "name": "方正细黑一",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZXiHei"],
    },
    {
        "name": "方正兰亭黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZLantingHei", "Lantinghei", "FZLT"],
    },
    {
        "name": "方正兰亭圆",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZLantingYuan"],
    },
    {
        "name": "方正悠黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZYouHei"],
    },
    {
        "name": "方正悠宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZYouSong"],
    },
    {
        "name": "方正正黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZZhengHei"],
    },
    {
        "name": "方正正纤黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZZhengXianHei"],
    },
    {
        "name": "方正大黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZDaHei"],
    },
    {
        "name": "方正粗黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZCuHei"],
    },
    {
        "name": "方正超粗黑",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZChaoCuHei"],
    },
    {
        "name": "方正雅宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZYaSong"],
    },
    {
        "name": "方正标雅宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZBiaoYaSong"],
    },
    {
        "name": "方正风雅宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZFengYaSong"],
    },
    {
        "name": "方正清刻本悦宋",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZQingKeBenYueSong"],
    },
    {
        "name": "方正宋刻本秀楷",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZSongKeBenXiuKai"],
    },
    {
        "name": "方正综艺",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZZongYi"],
    },
    {
        "name": "方正粗倩",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZCuQian"],
    },
    {
        "name": "方正胖娃",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZPangWa"],
    },
    {
        "name": "方正卡通",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZKaTong"],
    },
    {
        "name": "方正少儿",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZShaoEr"],
    },
    {
        "name": "方正稚艺",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZZhiYi"],
    },
    {
        "name": "方正喵呜",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZMiaoWu"],
    },
    {
        "name": "方正静蕾",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZJingLei"],
    },
    {
        "name": "方正启体",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZQiTi"],
    },
    {
        "name": "方正苏新诗柳楷",
        "foundry": "方正字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["FZSuXinShiLiuKai"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 汉仪字库 (Hanyi) — Most require paid license
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "汉仪旗黑",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYQiHei", "Hanyi Qi Hei"],
    },
    {
        "name": "汉仪楷体",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYKaiTi"],
    },
    {
        "name": "汉仪中黑",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYZhongHei"],
    },
    {
        "name": "汉仪大黑",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYDaHei"],
    },
    {
        "name": "汉仪超粗黑",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYChaoCuHei"],
    },
    {
        "name": "汉仪细圆",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYXiYuan"],
    },
    {
        "name": "汉仪中圆",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYZhongYuan"],
    },
    {
        "name": "汉仪粗圆",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYCuYuan"],
    },
    {
        "name": "汉仪菱心",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYLingXin"],
    },
    {
        "name": "汉仪综艺",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYZongYi"],
    },
    {
        "name": "汉仪小麦",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYXiaoMai"],
    },
    {
        "name": "汉仪润圆",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYRunYuan"],
    },
    {
        "name": "汉仪雅酷黑",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYYaKuHei"],
    },
    {
        "name": "汉仪力量黑",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYLiLiangHei"],
    },
    {
        "name": "汉仪赤云隶",
        "foundry": "汉仪字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["HYChiYunLi"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 华康字库 (Dynacomware) — Most require paid license
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "华康黑体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFHei", "Dynacomware Hei", "华康黑体W3", "华康黑体W5", "华康黑体W7"],
    },
    {
        "name": "华康宋体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFSong"],
    },
    {
        "name": "华康楷体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFKai"],
    },
    {
        "name": "华康仿宋",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFFangSong"],
    },
    {
        "name": "华康圆体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFYuan"],
    },
    {
        "name": "华康娃娃体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFWaWa"],
    },
    {
        "name": "华康少女文字",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFShaoNv"],
    },
    {
        "name": "华康海报体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFHaiBao"],
    },
    {
        "name": "华康俪金黑",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFLiJinHei"],
    },
    {
        "name": "华康瘦金体",
        "foundry": "华康字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["DFShouJin"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 站酷字体 — FREE for commercial use!
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "站酷快乐体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu KuaiLe", "站酷快乐"],
    },
    {
        "name": "站酷文艺体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu WenYi"],
    },
    {
        "name": "站酷高端黑",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu GaoDuanHei"],
    },
    {
        "name": "站酷酷黑",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu KuHei"],
    },
    {
        "name": "站酷小薇LOGO体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu XiaoWei LOGO"],
    },
    {
        "name": "站酷庆科黄油体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu QingKe HuangYou"],
    },
    {
        "name": "站酷仓耳舒圆体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu CangEr ShuYuan"],
    },
    {
        "name": "站酷鸿远御风体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu HongYuan YuFeng"],
    },
    {
        "name": "站酷冠宇快乐体",
        "foundry": "站酷",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZhanKu GuanYu KuaiLe"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 思源字体 (Source Han / Noto) — OPEN SOURCE, free commercial use
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "思源黑体",
        "foundry": "Adobe / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Source Han Sans", "Noto Sans CJK", "Source Han Sans SC", "思源黑体SC"],
        "official_url": "https://github.com/adobe-fonts/source-han-sans",
    },
    {
        "name": "思源宋体",
        "foundry": "Adobe / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Source Han Serif", "Noto Serif CJK", "Source Han Serif SC", "思源宋体SC"],
        "official_url": "https://github.com/adobe-fonts/source-han-serif",
    },
    {
        "name": "Noto Sans SC",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Noto Sans Simplified Chinese"],
        "official_url": "https://fonts.google.com/noto",
    },
    {
        "name": "Noto Serif SC",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Noto Serif Simplified Chinese"],
    },
    {
        "name": "Noto Sans TC",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Noto Sans Traditional Chinese"],
    },
    {
        "name": "Noto Sans HK",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Noto Sans Hong Kong"],
    },
    {
        "name": "Noto Sans JP",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Noto Sans Japanese"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 阿里巴巴字体 — FREE for commercial use!
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "阿里巴巴普惠体",
        "foundry": "阿里巴巴",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Alibaba PuHuiTi", "阿里普惠体", "普惠体", "Alibaba Sans"],
        "official_url": "https://www.alibabafonts.com",
    },
    {
        "name": "阿里巴巴普惠体 2.0",
        "foundry": "阿里巴巴",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Alibaba PuHuiTi 2.0"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 造字工房 — Mostly paid commercial license
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "造字工房悦黑",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF YueHei", "MakeFont YueHei"],
    },
    {
        "name": "造字工房尚黑",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF ShangHei"],
    },
    {
        "name": "造字工房朗倩",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF LangQian"],
    },
    {
        "name": "造字工房形黑",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF XingHei"],
    },
    {
        "name": "造字工房言宋",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF YanSong"],
    },
    {
        "name": "造字工房俊雅",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF JunYa"],
    },
    {
        "name": "造字工房丁丁",
        "foundry": "造字工房",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["MF DingDing"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 文鼎字库 (Arphic) — Some free, some paid
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "文鼎PL简中楷",
        "foundry": "文鼎字库",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["AR PL KaitiM GB"],
    },
    {
        "name": "文鼎PL细上海宋",
        "foundry": "文鼎字库",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["AR PL UMing"],
    },
    {
        "name": "文鼎中黑",
        "foundry": "文鼎字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["AR ZhongHei"],
    },
    {
        "name": "文鼎粗黑",
        "foundry": "文鼎字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["AR CuHei"],
    },
    {
        "name": "文鼎圆体",
        "foundry": "文鼎字库",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": ["AR YuanTi"],
    },

    # ═══════════════════════════════════════════════════════════════
    # 更多中文字体
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "锐字真言体",
        "foundry": "锐字工房",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["RuiZi ZhenYan"],
    },
    {
        "name": "庞门正道标题体",
        "foundry": "庞门正道",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["PangMen ZhengDao BiaoTi"],
    },
    {
        "name": "庞门正道轻松体",
        "foundry": "庞门正道",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["PangMen ZhengDao QingSong"],
    },
    {
        "name": "优设标题黑",
        "foundry": "优设",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["YouShe BiaoTiHei"],
    },
    {
        "name": "优设好身体",
        "foundry": "优设",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["YouShe HaoShenTi"],
    },
    {
        "name": "杨任东竹石体",
        "foundry": "杨任东",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["YangRenDong ZhuShi"],
    },
    {
        "name": "演示悠然小楷",
        "foundry": "演示字体",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["YanShi YouRan XiaoKai"],
    },
    {
        "name": "演示佛系体",
        "foundry": "演示字体",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["YanShi FoXi"],
    },
    {
        "name": "江西拙楷",
        "foundry": "黄令东",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["JiangXi ZhuoKai"],
    },
    {
        "name": "霞鹜文楷",
        "foundry": "LXGW",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["LXGW WenKai", "霞鹜文楷 GB"],
        "official_url": "https://github.com/lxgw/LxgwWenKai",
    },
    {
        "name": "霞鹜漫黑",
        "foundry": "LXGW",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["LXGW ManHei"],
    },
    {
        "name": "霞鹜新致宋",
        "foundry": "LXGW",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["LXGW XinZhiSong"],
    },
    {
        "name": "猫啃网什锦体",
        "foundry": "猫啃网",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["MaoKen Wang ShiJin"],
    },
    {
        "name": "猫啃网糖圆体",
        "foundry": "猫啃网",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["MaoKen Wang TangYuan"],
    },
    {
        "name": "得意黑",
        "foundry": "atelierAnchor",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Smiley Sans", "SmileySans"],
        "official_url": "https://github.com/atelier-anchor/smiley-sans",
    },
    {
        "name": "OPlus楷体",
        "foundry": "OPlus",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["OPlus KaiTi"],
    },
    {
        "name": "沐瑶软笔手写体",
        "foundry": "沐瑶",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["MuYao RuanBi"],
    },
    {
        "name": "字由芳华体",
        "foundry": "字由",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["ZiYou FangHua"],
    },
    {
        "name": "素材集市康康体",
        "foundry": "素材集市",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["SuCai JiShi KangKang"],
    },
    {
        "name": "谐谑彩色字体",
        "foundry": "谐谑",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["XieXue CaiSe"],
    },
    {
        "name": "台湾教育部标准楷书",
        "foundry": "台湾教育部",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["TW-MOE-Standard-Kai"],
    },
    {
        "name": "台湾教育部标准宋体",
        "foundry": "台湾教育部",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["TW-MOE-Standard-Song"],
    },
    {
        "name": "全字库楷体",
        "foundry": "全字库",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["TW-Kai", "全字库正楷体"],
    },
    {
        "name": "全字库宋体",
        "foundry": "全字库",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["TW-Sung"],
    },
    {
        "name": "更纱黑体",
        "foundry": "Sarasa Project",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Sarasa Gothic", "更纱黑体 SC"],
        "official_url": "https://github.com/be5invis/Sarasa-Gothic",
    },
    {
        "name": "微软雅黑",
        "foundry": "Microsoft",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["Microsoft YaHei", "微软雅黑 UI", "MS YaHei"],
        "notes": "Windows系统自带，但商业使用（嵌入/再分发）需要授权",
    },
    {
        "name": "苹方",
        "foundry": "Apple",
        "license_type": "free_commercial",
        "commercial_use": True,
        "embedding_allowed": True,
        "aliases": ["PingFang SC", "PingFang HK", "PingFang TC", "苹方-简", "苹方-繁"],
        "notes": "Apple系统自带，可用于macOS/iOS应用内展示",
    },

    # ═══════════════════════════════════════════════════════════════
    # Common System / English Fonts
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "Arial",
        "foundry": "Monotype",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "embedding_allowed": True,
        "aliases": ["Arial MT", "Arial Regular"],
    },
    {
        "name": "Arial Black",
        "foundry": "Monotype",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Times New Roman",
        "foundry": "Monotype",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "embedding_allowed": True,
        "aliases": ["Times New Roman PS", "TNR"],
    },
    {
        "name": "Georgia",
        "foundry": "Microsoft",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Verdana",
        "foundry": "Microsoft",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Trebuchet MS",
        "foundry": "Microsoft",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Comic Sans MS",
        "foundry": "Microsoft",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Impact",
        "foundry": "Microsoft",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Courier New",
        "foundry": "Monotype",
        "license_type": "free_commercial",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["Courier"],
    },
    {
        "name": "Helvetica",
        "foundry": "Monotype",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["Helvetica Neue", "Helvetica LT"],
        "notes": "系统自带可显示，但字体文件商业使用需授权",
    },
    {
        "name": "Helvetica Neue",
        "foundry": "Monotype",
        "license_type": "paid",
        "commercial_use": False,
        "aliases": [],
    },

    # ═══════════════════════════════════════════════════════════════
    # Google Fonts — FREE for commercial use (SIL OFL / Apache 2.0)
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "Roboto",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "embedding_allowed": True,
        "aliases": ["Roboto Regular", "Roboto Bold", "Roboto Thin"],
        "official_url": "https://fonts.google.com/specimen/Roboto",
    },
    {
        "name": "Roboto Slab",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Roboto Mono",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Roboto Condensed",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Open Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "embedding_allowed": True,
        "aliases": ["Open Sans Regular", "OpenSans"],
        "official_url": "https://fonts.google.com/specimen/Open+Sans",
    },
    {
        "name": "Open Sans Condensed",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Lato",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Lato Regular", "Lato Bold"],
    },
    {
        "name": "Montserrat",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Montserrat Regular"],
        "official_url": "https://fonts.google.com/specimen/Montserrat",
    },
    {
        "name": "Poppins",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Poppins Regular"],
    },
    {
        "name": "Raleway",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "PT Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "PT Serif",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Oswald",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Source Sans Pro",
        "foundry": "Adobe / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Source Sans 3", "Source Sans Pro"],
    },
    {
        "name": "Source Serif Pro",
        "foundry": "Adobe / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Source Serif 4", "Source Serif Pro"],
    },
    {
        "name": "Source Code Pro",
        "foundry": "Adobe / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Nunito",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Nunito Sans"],
    },
    {
        "name": "Nunito Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Ubuntu",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Ubuntu Regular"],
    },
    {
        "name": "Playfair Display",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Merriweather",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [
            "Merriweather Regular", "Merriweather Sans",
        ],
    },
    {
        "name": "Merriweather Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Fira Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Fira Code",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Fira Mono",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Inter",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Inter Regular"],
        "official_url": "https://fonts.google.com/specimen/Inter",
    },
    {
        "name": "Work Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Libre Franklin",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Quicksand",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "DM Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "DM Serif Display",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Barlow",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Space Grotesk",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Space Mono",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "JetBrains Mono",
        "foundry": "JetBrains",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Archivo",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Archivo Black", "Archivo Narrow"],
    },
    {
        "name": "Archivo Black",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Crimson Text",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Crimson Pro",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "EB Garamond",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Libre Baskerville",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Josefin Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Rubik",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Heebo",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Assistant",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },

    # ═══════════════════════════════════════════════════════════════
    # Adobe Fonts (Typekit) — Licensed via Creative Cloud
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "Proxima Nova",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "embedding_allowed": True,
        "web_font_allowed": True,
        "aliases": [],
        "notes": "通过 Adobe Creative Cloud 订阅可使用",
    },
    {
        "name": "Futura PT",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["Futura"],
    },
    {
        "name": "Minion Pro",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["Minion"],
    },
    {
        "name": "Myriad Pro",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": ["Myriad"],
    },
    {
        "name": "Adobe Caslon Pro",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Garamond Premier Pro",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Acumin Pro",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },
    {
        "name": "Brandon Grotesque",
        "foundry": "Adobe Fonts",
        "license_type": "paid",
        "commercial_use": True,
        "requires_attribution": False,
        "aliases": [],
    },

    # ═══════════════════════════════════════════════════════════════
    # More popular free/open English fonts
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "Manrope",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Outfit",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Plus Jakarta Sans",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Figtree",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Satoshi",
        "foundry": "Fontshare",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Cabinet Grotesk",
        "foundry": "Fontshare",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Clash Display",
        "foundry": "Fontshare",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "General Sans",
        "foundry": "Fontshare",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Supreme",
        "foundry": "Fontshare",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Chillax",
        "foundry": "Fontshare",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },

    # ═══════════════════════════════════════════════════════════════
    # Other popular fonts (mixed licenses)
    # ═══════════════════════════════════════════════════════════════
    {
        "name": "DIN",
        "foundry": "Various",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["DIN Pro", "DIN Next", "FF DIN"],
        "notes": "DIN 字体有多种版本，大部分商业使用需授权",
    },
    {
        "name": "Gotham",
        "foundry": "Hoefler & Co.",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["Gotham Bold", "Gotham Book"],
    },
    {
        "name": "Circular",
        "foundry": "Lineto",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["Circular Std", "Circular Spotify"],
    },
    {
        "name": "Gilroy",
        "foundry": "Radomir Tinkov",
        "license_type": "free_personal",
        "commercial_use": False,
        "requires_attribution": True,
        "aliases": ["Gilroy Regular", "Gilroy Bold", "Gilroy Light"],
        "notes": "个人免费，商业使用需购买授权",
    },
    {
        "name": "Avenir",
        "foundry": "Monotype",
        "license_type": "paid",
        "commercial_use": False,
        "requires_attribution": None,
        "aliases": ["Avenir Next", "Avenir LT"],
    },
    {
        "name": "Bebas Neue",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": ["Bebas"],
    },
    {
        "name": "Lobster",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Pacifico",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Dancing Script",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Caveat",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Permanent Marker",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Amatic SC",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Anton",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Arimo",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Inconsolata",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Titillium Web",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Abril Fatface",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Comfortaa",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Righteous",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Monoton",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "Press Start 2P",
        "foundry": "Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "IBM Plex Sans",
        "foundry": "IBM / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "IBM Plex Serif",
        "foundry": "IBM / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
    {
        "name": "IBM Plex Mono",
        "foundry": "IBM / Google",
        "license_type": "open_source",
        "commercial_use": True,
        "requires_attribution": False,
        "web_font_allowed": True,
        "aliases": [],
    },
]


def seed_database():
    """Seed the font license database."""
    settings = get_settings()

    # Use sync engine for seeding
    sync_url = settings.DATABASE_URL.replace("+asyncpg", "+psycopg2").replace(
        "postgresql+psycopg2://", "postgresql://"
    )
    engine = create_engine(sync_url)

    # Create tables
    Base.metadata.create_all(engine)

    with Session(engine) as session:
        # Check if already seeded
        existing = session.execute(select(Font).limit(1)).scalar_one_or_none()
        if existing:
            print(f"Font database already contains data ({session.query(Font).count()} fonts).")
            overwrite = input("Overwrite? (y/N): ").strip().lower()
            if overwrite != "y":
                print("Skipping seed.")
                return
            # Clear existing data
            session.query(FontAlias).delete()
            session.query(Font).delete()
            session.commit()

        count = 0
        for font_data in FONTS_DATA:
            aliases = font_data.pop("aliases", [])

            font = Font(**font_data)
            session.add(font)
            session.flush()  # Get the font ID

            for alias in aliases:
                fa = FontAlias(font_id=font.id, alias=alias)
                session.add(fa)

            count += 1

        session.commit()
        print(f"Successfully seeded {count} fonts with aliases.")

        # Print summary
        free = session.query(Font).filter(Font.commercial_use == True).count()
        paid = session.query(Font).filter(Font.commercial_use == False).count()
        unknown = session.query(Font).filter(Font.commercial_use == None).count()
        print(f"  - Free commercial: {free}")
        print(f"  - Paid/restricted: {paid}")
        print(f"  - Unknown: {unknown}")


if __name__ == "__main__":
    seed_database()
