"""
Report generation service.

Assembles all analysis findings into a structured JSON report
with a human-readable Chinese summary generated by Claude.
"""

from typing import Optional, List
import logging

logger = logging.getLogger(__name__)


def generate_report(
    font_risks: List[dict],
    source_risk: Optional[dict],
    api_key: str,
    ai_provider: str = "",
) -> dict:
    """Generate the final structured analysis report."""
    # Deduplicate: merge fonts with same name + risk, collect text samples
    merged = {}
    for fr in font_risks:
        key = (fr["name"], fr["risk"])
        if key not in merged:
            merged[key] = {
                "name": fr["name"],
                "risk": fr["risk"],
                "explanation": fr["explanation"],
                "alternatives": list(fr.get("alternatives", [])),
                "text_samples": [],
            }
        # Collect unique text samples — prefer individual items over pre-joined
        sample = fr.get("text_sample", "")
        if sample and " | " in sample:
            # Pre-joined text from old format — split into individual items
            for item in sample.split(" | "):
                item = item.strip()
                if item and item not in merged[key]["text_samples"]:
                    merged[key]["text_samples"].append(item)
        elif sample and sample not in merged[key]["text_samples"]:
            merged[key]["text_samples"].append(sample)

    risks = [m["risk"] for m in merged.values()]
    if source_risk:
        risks.append(source_risk["risk"])

    if "red" in risks:
        overall_risk = "red"
    elif "yellow" in risks:
        overall_risk = "yellow"
    else:
        overall_risk = "green"

    font_results = []
    for m in merged.values():
        entry = {
            "name": m["name"],
            "risk": m["risk"],
            "explanation": m["explanation"],
            "alternatives": m["alternatives"],
        }
        if m["text_samples"]:
            entry["detected_text"] = m["text_samples"][:10]  # Max 10 samples
        font_results.append(entry)

    image_source_result = None
    if source_risk:
        image_source_result = {
            "source_url": source_risk.get("source_url", ""),
            "risk": source_risk["risk"],
            "explanation": source_risk["explanation"],
            "alternatives": source_risk.get("alternatives", []),
        }

    summary = _generate_summary(
        overall_risk=overall_risk,
        font_results=font_results,
        image_source_result=image_source_result,
        api_key=api_key,
        ai_provider=ai_provider,
    )

    return {
        "overall_risk": overall_risk,
        "fonts": font_results,
        "image_source": image_source_result,
        "summary": summary,
    }


def _generate_summary(
    overall_risk: str,
    font_results: List[dict],
    image_source_result: Optional[dict],
    api_key: str,
    ai_provider: str = "",
) -> str:
    """Generate a human-readable Chinese summary using Claude."""
    risk_labels = {"green": "低风险", "yellow": "中风险", "red": "高风险"}

    context_parts = [f"整体风险等级：{risk_labels.get(overall_risk, overall_risk)}"]

    if font_results:
        context_parts.append("\n字体检测结果：")
        for f in font_results:
            context_parts.append(
                f"- {f['name']}: {risk_labels.get(f['risk'], f['risk'])} - {f['explanation']}"
            )

    if image_source_result:
        context_parts.append(
            f"\n图片来源检测：{risk_labels.get(image_source_result['risk'], image_source_result['risk'])} - {image_source_result['explanation']}"
        )

    context = "\n".join(context_parts)

    from app.services.ai_client import is_ai_available
    ai_ok = is_ai_available(api_key=api_key)
    ai_attempted = False
    ai_error = ""
    logger.info(f"Generate summary: ai_available={ai_ok}, api_key={'SET' if api_key else 'EMPTY'}, provider='{ai_provider or '(default)'}'")
    if ai_ok:
        try:
            from app.services.ai_client import call_ai_text

            prompt = f"""你是一个版权合规助手。请用友好、专业的语气，用简体中文为用户总结以下图片版权检测结果。

{context}

要求：
1. 用2-3段简洁的文字总结
2. 如果有高风险（红色）项目，请明确指出并建议行动方案
3. 如果有中风险（黄色）项目，提醒用户注意
4. 如果全部低风险（绿色），恭喜用户
5. 语气亲切，像一位帮助设计师的朋友
6. 不要使用markdown格式

请直接输出总结文本："""

            summary = call_ai_text(
                api_key=api_key,
                prompt=prompt,
                provider=ai_provider,
                max_tokens=1000,
                temperature=0.5,
            )
            logger.info(f"AI summary generated successfully ({len(summary)} chars)")
            return summary.strip()

        except Exception as e:
            ai_attempted = True
            ai_error = str(e)[:200]
            logger.exception(f"AI summary generation failed: {e}")

    logger.info("Using fallback (rule-based) summary")
    return _fallback_summary(overall_risk, font_results, image_source_result, ai_attempted, ai_error)


def _fallback_summary(
    overall_risk: str,
    font_results: List[dict],
    image_source_result: Optional[dict],
    ai_attempted: bool = False,
    ai_error: str = "",
) -> str:
    """Generate a rule-based Chinese summary without AI."""
    red_count = sum(1 for f in font_results if f["risk"] == "red")
    yellow_count = sum(1 for f in font_results if f["risk"] == "yellow")
    green_count = sum(1 for f in font_results if f["risk"] == "green")

    # Collect detected text samples for context
    all_text = []
    for f in font_results:
        for t in f.get("detected_text", [])[:3]:
            if t and t not in all_text and not t.startswith("["):
                all_text.append(t)

    parts = []

    # Opening: detected text summary
    if all_text:
        parts.append(f"从您的图片中检测到以下文字内容：{'、'.join(all_text[:8])}。")

    if overall_risk == "red":
        parts.append(f"您的设计中存在 {red_count} 项高风险和 {yellow_count} 项中风险项目。")
        parts.append("高风险字体可能涉及商业侵权，建议您立即替换为免费商用字体。")
        red_fonts = [f["name"] for f in font_results if f["risk"] == "red"]
        if red_fonts:
            parts.append(f"需要替换的字体：{'、'.join(red_fonts)}。")
        if image_source_result and image_source_result["risk"] == "red":
            parts.append(f"图片来源 {image_source_result.get('source_url', '未知')} 也存在版权风险，建议使用 Unsplash、Pexels 等免费图库替代。")

    elif overall_risk == "yellow":
        if yellow_count > 1:
            parts.append(f"共检测到 {yellow_count} 种不同的字体样式，均未在本地字体库中匹配到具体名称。")
        else:
            parts.append("检测到的字体未能在本地字体库中匹配到具体名称。")

        if ai_attempted:
            # AI was configured but the call failed
            parts.append("⚠️ AI 识别已尝试但调用失败，可能是密钥无效或网络问题。请检查您的 API 密钥是否正确，或尝试切换 AI 供应商。")
            if ai_error:
                parts.append(f"错误详情：{ai_error}")
        else:
            # AI not configured at all
            parts.append("⚠️ 字体识别需要 AI 视觉模型。请点击上方的齿轮图标，输入您的 API 密钥以启用 AI 字体识别（支持 Claude、OpenAI、Gemini、Kimi）。")
        parts.append("在未启用 AI 识别的情况下，建议您手动确认相关字体的商业授权条款。")
        if image_source_result and image_source_result["risk"] == "yellow":
            parts.append("图片来源可能需要署名或购买授权，请注意查看原网站的许可协议。")

    else:
        parts.append("恭喜！您的设计在版权合规方面表现良好，所有检测项目均为低风险。")
        parts.append("检测到的字体均可免费商用，图片来源安全可靠。")

    parts.append("\nLicenseLight 建议您定期检查设计中的字体和图片授权，为您的创作保驾护航。")

    return "".join(parts)
