"""
Report generation service.
"""

from typing import Optional, List

Assembles all analysis findings into a structured JSON report
with a human-readable Chinese summary generated by Claude.
"""

import logging
import json

logger = logging.getLogger(__name__)


def generate_report(
    font_risks: List[dict],
    source_risk: Optional[dict],
    claude_api_key: str,
) -> dict:
    """
    Generate the final structured analysis report.

    Args:
        font_risks: Classified font risk assessments.
        source_risk: Classified image source risk assessment.
        claude_api_key: Anthropic API key for summary generation.

    Returns:
        Full report dict matching the AnalysisReport schema.
    """
    # Determine overall risk
    risks = [f["risk"] for f in font_risks]
    if source_risk:
        risks.append(source_risk["risk"])

    if "red" in risks:
        overall_risk = "red"
    elif "yellow" in risks:
        overall_risk = "yellow"
    else:
        overall_risk = "green"

    # Build font results
    font_results = []
    for fr in font_risks:
        font_results.append(
            {
                "name": fr["name"],
                "risk": fr["risk"],
                "explanation": fr["explanation"],
                "alternatives": fr.get("alternatives", []),
            }
        )

    # Build image source result
    image_source_result = None
    if source_risk:
        image_source_result = {
            "source_url": source_risk.get("source_url", ""),
            "risk": source_risk["risk"],
            "explanation": source_risk["explanation"],
            "alternatives": source_risk.get("alternatives", []),
        }

    # Generate Chinese summary via Claude
    summary = _generate_summary(
        overall_risk=overall_risk,
        font_results=font_results,
        image_source_result=image_source_result,
        claude_api_key=claude_api_key,
    )

    return {
        "overall_risk": overall_risk,
        "fonts": font_results,
        "image_source": image_source_result,
        "summary": summary,
    }


def _generate_summary(
    overall_risk: str,
    font_results: List[dict],
    image_source_result: Optional[dict],
    claude_api_key: str,
) -> str:
    """
    Generate a human-readable Chinese summary using Claude.

    Falls back to a rule-based summary if Claude is unavailable.
    """
    # Build context for Claude
    risk_labels = {"green": "低风险 ✅", "yellow": "中风险 ⚠️", "red": "高风险 ❌"}

    context_parts = [f"整体风险等级：{risk_labels.get(overall_risk, overall_risk)}"]

    if font_results:
        context_parts.append("\n字体检测结果：")
        for f in font_results:
            context_parts.append(
                f"- {f['name']}: {risk_labels.get(f['risk'], f['risk'])} - {f['explanation']}"
            )

    if image_source_result:
        context_parts.append(
            f"\n图片来源检测：{risk_labels.get(image_source_result['risk'], image_source_result['risk'])} - {image_source_result['explanation']}"
        )

    context = "\n".join(context_parts)

    # Try Claude
    if claude_api_key:
        try:
            from app.services.claude_client import call_claude_text

            prompt = f"""你是一个版权合规助手。请用友好、专业的语气，用简体中文为用户总结以下图片版权检测结果。

{context}

要求：
1. 用2-3段简洁的文字总结
2. 如果有高风险（红色）项目，请明确指出并建议行动方案
3. 如果有中风险（黄色）项目，提醒用户注意
4. 如果全部低风险（绿色），恭喜用户
5. 语气亲切，像一位帮助设计师的朋友
6. 不要使用emoji，不要用markdown格式

请直接输出总结文本："""

            summary = call_claude_text(
                api_key=claude_api_key,
                prompt=prompt,
                max_tokens=1000,
                temperature=0.5,
            )
            return summary.strip()

        except Exception as e:
            logger.warning(f"Claude summary generation failed: {e}")

    # Fallback: rule-based summary
    return _fallback_summary(overall_risk, font_results, image_source_result)


def _fallback_summary(
    overall_risk: str,
    font_results: List[dict],
    image_source_result: Optional[dict],
) -> str:
    """Generate a rule-based Chinese summary without Claude."""

    red_count = sum(1 for f in font_results if f["risk"] == "red")
    yellow_count = sum(1 for f in font_results if f["risk"] == "yellow")
    green_count = sum(1 for f in font_results if f["risk"] == "green")

    parts = []

    if overall_risk == "red":
        parts.append(
            f"您的设计中存在 {red_count} 项高风险和 {yellow_count} 项中风险项目。"
        )
        parts.append("高风险字体可能涉及商业侵权，建议您立即替换为免费商用字体。")
        # Mention specific red fonts
        red_fonts = [f["name"] for f in font_results if f["risk"] == "red"]
        if red_fonts:
            parts.append(f"需要替换的字体：{'、'.join(red_fonts)}。")

        if image_source_result and image_source_result["risk"] == "red":
            parts.append(f"图片来源 {image_source_result.get('source_url', '未知')} 也存在版权风险，建议使用 Unsplash、Pexels 等免费图库替代。")

    elif overall_risk == "yellow":
        parts.append(
            f"您的设计整体风险可控，但存在 {yellow_count} 项需要留意的项目。"
        )
        parts.append("建议您在使用前确认相关字体的商业授权条款，避免潜在风险。")

        if image_source_result and image_source_result["risk"] == "yellow":
            parts.append("图片来源可能需要署名或购买授权，请注意查看原网站的许可协议。")

    else:
        parts.append("恭喜！您的设计在版权合规方面表现良好，所有检测项目均为低风险。")
        parts.append("检测到的字体均可免费商用，图片来源安全可靠。")

    parts.append("\nLicenseLight 建议您定期检查设计中的字体和图片授权，为您的创作保驾护航。")

    return "".join(parts)
